name: fuel-cycle-paper
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - matplotlib
  - ipykernel
  - scipy
  # - festim
  - python-gmsh
  - scifem
  - fenics-dolfinx
  - pip
  - pip:
    - git+https://github.com/festim-dev/PathView@glc
    - git+https://github.com/festim-dev/festim@fenicsx
    - morethemes